certs:
  basedir: ../certs
spring:
  ssl:
    bundle:
      pem:
        server:
          truststore:
            certificate: ${certs.basedir}/server/ca.crt
          keystore:
            certificate: ${certs.basedir}/server/server.crt
            privateKey: ${certs.basedir}/server/server.key
server:
  ssl:
    bundle: server
    client-auth: none
