base-url: https://server.192.168.86.46.nip.io:8686
certs:
  basedir: ../certs
spring:
  ssl:
    bundle:
      pem:
        client:
          truststore:
            certificate: ${certs.basedir}/client/ca.crt
